repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: &flake8_version 7.3.0
    hooks:
      - &flake8_hook
        id: flake8
        additional_dependencies:
          - flake8-annotations~=3.2
          - flake8-bugbear==25.11.29
          - flake8-docstrings~=1.7
          - flake8-string-format~=0.4.0
          - flake8-todo~=0.7
          - pep8-naming~=0.15.1
          - pydocstyle~=6.3
  - repo: https://github.com/PyCQA/flake8
    rev: *flake8_version
    hooks:
      - <<: *flake8_hook
        alias: flake8-annotate
        name: flake8 (with annotations)
        stages: [manual]
        args: [
          --format,
          "::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s",
        ]
