name: Create Sentry release

on:
  push:
    branches:
      - main

jobs:
  create_sentry_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # The version script relies on history. Fetch 100 commits to be safe.
          fetch-depth: 100

      - name: Get version
        id: version
        run: |
          set -eu
          version=$(python scripts/version.py)
          echo "version=$version" >> $GITHUB_OUTPUT
          printf "%s\n" "${version}"

      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: python-discord
          SENTRY_PROJECT: snekbox
        with:
          version: ${{ steps.version.outputs.version }}
          environment: production
          version_prefix: snekbox@
